-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 19:40:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Tipo` (
  `idCliente Tipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Identificação` VARCHAR(45) NOT NULL,
  `idCliente Tipo` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `Nome` (`Nome` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente Tipo1_idx` (`idCliente Tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente Tipo1`
    FOREIGN KEY (`idCliente Tipo`)
    REFERENCES `mydb`.`Cliente Tipo` (`idCliente Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL COMMENT 'CARTÃO\nBOLETO\nPIX\n',
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status Entrega` (
  `idStatus Entrega` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus Entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `Codigo de Rastreio` VARCHAR(45) NOT NULL,
  `idStatus Entrega` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_Entrega_Status Entrega1_idx` (`idStatus Entrega` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Status Entrega1`
    FOREIGN KEY (`idStatus Entrega`)
    REFERENCES `mydb`.`Status Entrega` (`idStatus Entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NULL,
  `Frete` FLOAT NOT NULL,
  `idCliente` INT NOT NULL,
  `idPagamento` INT NOT NULL,
  `idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Pagamento1_idx` (`idPagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pagamento1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `Valor` (`Valor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Pedido Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Pedido Produto` (
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`idPedido` ASC) INVISIBLE,
  INDEX `Quantidade` (`Quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `Categoria` (`Categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Categoria Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Categoria Produto` (
  `idCategoria` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `idProduto`),
  INDEX `fk_Categoria_has_Produto_Produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Produto_Categoria1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Produto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Produto Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Produto Estoque` (
  `idProduto` INT NOT NULL,
  `idEstoque` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `Quantidade` (`Quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceiro - Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Terceiro - Vendedor` (
  `idTerceiro - Vendedor` INT NOT NULL AUTO_INCREMENT,
  `Razão Social` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`),
  INDEX `Razão Social` (`Razão Social` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Terceiro - Vendedor Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Terceiro - Vendedor Produto` (
  `idTerceiro - Vendedor` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`, `idProduto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`idTerceiro - Vendedor` ASC) VISIBLE,
  INDEX `Quantidade` (`Quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`idTerceiro - Vendedor`)
    REFERENCES `mydb`.`Terceiro - Vendedor` (`idTerceiro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Razão Social` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  INDEX `CNPJ` (`CNPJ` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Fornecedor Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Fornecedor Produto` (
  `idFornecedor` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`, `idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo Endereço` (
  `idTipo Endereço` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL COMMENT 'Casa/Serviço\n',
  PRIMARY KEY (`idTipo Endereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Endereço` (
  `idCliente Endereço` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  `Referência` VARCHAR(45) NULL,
  `Complemento` VARCHAR(45) NULL,
  `idTipo Endereço` INT NOT NULL,
  PRIMARY KEY (`idCliente Endereço`, `idTipo Endereço`),
  INDEX `fk_Cliente Endereço_Tipo Endereço1_idx` (`idTipo Endereço` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Endereço_Tipo Endereço1`
    FOREIGN KEY (`idTipo Endereço`)
    REFERENCES `mydb`.`Tipo Endereço` (`idTipo Endereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Cliente Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Cliente Endereço` (
  `idCliente` INT NOT NULL,
  `idCliente Endereço` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idCliente Endereço`),
  INDEX `fk_Cliente_has_Cliente Endereço_Cliente Endereço1_idx` (`idCliente Endereço` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Cliente Endereço_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Cliente Endereço_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Cliente Endereço_Cliente Endereço1`
    FOREIGN KEY (`idCliente Endereço`)
    REFERENCES `mydb`.`Cliente Endereço` (`idCliente Endereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Físico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Físico` (
  `idCliente Físico` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente Físico`, `Cliente_idCliente`),
  INDEX `fk_Cliente Físico_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Físico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Juridico` (
  `idCliente Juridico` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente Juridico`, `Cliente_idCliente`),
  INDEX `fk_Cliente Juridico_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Juridico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartões`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartões` (
  `idCartões` INT NOT NULL AUTO_INCREMENT,
  `Número` VARCHAR(45) NOT NULL,
  `Data Validade` DATE NOT NULL,
  `Nome do cartão` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCartões`, `Cliente_idCliente`),
  INDEX `fk_Cartões_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cartões_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
