-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 18:04:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_tipo` (
  `id_cliente_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `identificacao` VARCHAR(45) NOT NULL,
  `id_cliente_tipo` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `Nome` (`nome` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente Tipo1_idx` (`id_cliente_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente Tipo1`
    FOREIGN KEY (`id_cliente_tipo`)
    REFERENCES `mydb`.`cliente_tipo` (`id_cliente_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'CARTÃO\nBOLETO\nPIX\n',
  PRIMARY KEY (`id_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_entrega` (
  `id_status_ntrega` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_ntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `codigo_de_rastreio` VARCHAR(45) NOT NULL,
  `id_statusEntrega` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_Entrega_Status Entrega1_idx` (`id_statusEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Status Entrega1`
    FOREIGN KEY (`id_statusEntrega`)
    REFERENCES `mydb`.`status_entrega` (`id_status_ntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `frete` FLOAT NOT NULL,
  `idCliente` INT NOT NULL,
  `id_pagamento` INT NOT NULL,
  `id_entrega` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedido_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Pagamento1_idx` (`id_pagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`id_entrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pagamento1`
    FOREIGN KEY (`id_pagamento`)
    REFERENCES `mydb`.`pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`id_entrega`)
    REFERENCES `mydb`.`entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `Valor` (`valor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_pedido_produto` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_produto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`id_pedido` ASC) INVISIBLE,
  INDEX `Quantidade` (`quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `mydb`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `Categoria` (`categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_categoria_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_categoria_produto` (
  `id_categoria` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_categoria`, `id_produto`),
  INDEX `fk_Categoria_has_Produto_Produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Produto_Categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Produto_Categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Produto_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id_estoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_produto_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_produto_estoque` (
  `id_produto` INT NOT NULL,
  `id_estoque` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_estoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`id_estoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `Quantidade` (`quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`id_estoque`)
    REFERENCES `mydb`.`estoque` (`id_estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terceiro_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terceiro_vendedor` (
  `id_terceiro_vendedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id_terceiro_vendedor`),
  INDEX `Razão Social` (`razao_social` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_terceiro_vendedor_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_terceiro_vendedor_produto` (
  `id_terceiro_endedor` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_terceiro_endedor`, `id_produto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`id_terceiro_endedor` ASC) VISIBLE,
  INDEX `Quantidade` (`quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`id_terceiro_endedor`)
    REFERENCES `mydb`.`terceiro_vendedor` (`id_terceiro_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  INDEX `CNPJ` (`cnpj` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_fornecedor_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_fornecedor_produto` (
  `id_fornecedor` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor`, `id_produto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_endereço` (
  `id_tipo_endereço` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Casa/Serviço\n',
  PRIMARY KEY (`id_tipo_endereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_endereço` (
  `id_Cliente_endereço` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `referencial` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `id_tipo_endereço` INT NOT NULL,
  PRIMARY KEY (`id_Cliente_endereço`, `id_tipo_endereço`),
  INDEX `fk_Cliente Endereço_Tipo Endereço1_idx` (`id_tipo_endereço` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Endereço_Tipo Endereço1`
    FOREIGN KEY (`id_tipo_endereço`)
    REFERENCES `mydb`.`tipo_endereço` (`id_tipo_endereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacao_cliente_endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacao_cliente_endereço` (
  `id_cliente` INT NOT NULL,
  `id_cliente_endereço` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_cliente_endereço`),
  INDEX `fk_Cliente_has_Cliente Endereço_Cliente Endereço1_idx` (`id_cliente_endereço` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Cliente Endereço_Cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Cliente Endereço_Cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Cliente Endereço_Cliente Endereço1`
    FOREIGN KEY (`id_cliente_endereço`)
    REFERENCES `mydb`.`cliente_endereço` (`id_Cliente_endereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_fisico` (
  `id_cliente_fisico` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente_fisico`, `cliente_id_cliente`),
  INDEX `fk_Cliente Físico_Cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Físico_Cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_juridico` (
  `idCliente Juridico` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`idCliente Juridico`, `Cliente_id_cliente`),
  INDEX `fk_Cliente Juridico_Cliente1_idx` (`Cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente Juridico_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartoes` (
  `idcartoes` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `Data Validade` DATE NOT NULL,
  `nome_do_cartao` VARCHAR(45) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`idcartoes`, `cliente_id_cliente`),
  INDEX `fk_Cartões_Cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cartões_Cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
